server:
  port: 8080

spring:
  application:
    name: board

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: test
    password: test
    hikari:
      maximum-pool-size: 20

  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: 1000ms

  data:
    web:
      pageable:
        one-indexed-parameters: true

  aop:
    auto: true

logging:
  level:
    root: INFO
    org:
      hibernate: DEBUG
