spring:
  profiles:
    active: dev
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:h2:mem:testdb  # 메모리 내 데이터베이스 사용
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    # In-memory DB이므로, 디스크 기반 DB로 설정할 수도 있습니다.
    # url: jdbc:h2:~/testdb
    # 외부 H2 DB를 사용하려면 해당 URL을 설정하면 됩니다.
  h2:
    console:
      enabled: true  # H2 콘솔 활성화 (브라우저에서 접근 가능)
      path: /h2-console  # H2 콘솔 URL 경로 설정
  jpa:
    hibernate:
      ddl-auto: update  # 자동으로 DB 스키마 업데이트 (create, update, validate, none 중 선택)
    database-platform: org.hibernate.dialect.H2Dialect  # H2에 맞는 Hibernate Dialect 설정
    show-sql: true  # 실행되는 SQL을 로그로 출력


  aop:
    auto: true

logging:
  level:
    org:
      hibernate: DEBUG
